### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-team-pro#1]
[elicitacion de requisitos iHome.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-team-pro/files/7590441/elicitacion.de.requisitos.iHome.pdf)

**Comment by JazminloRI** [comment]
CAL: 25.2%

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143178255-98fa8b92-c704-40d2-a65e-02ecd2bb438b.png)
Los requsitos deben ser en infinitivo

**Comment by josealfredo79** [comment]
La estructura de un Documento de especificacion de Requerimientos
Objetivo 
Requisitos de Informacion
Requisitos Funcionales
Requsitos No Funcionales

**Comment by christopheremv** [comment]
[elicitacion de requisitos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-team-pro/files/7634922/elicitacion.de.requisitos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
